# Generated by Django 3.0.3 on 2022-05-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('first_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Apellido')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], help_text='Género según DNI', null=True, verbose_name='Género')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Número de Doc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
