# Generated by Django 3.0.3 on 2022-05-11 23:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=19, verbose_name='Monto total en la orden')),
                ('status', models.SmallIntegerField(choices=[(0, 'Borrador'), (1, 'Rechazada'), (2, 'Aprobada'), (3, 'Autorizada'), (4, 'Otorgada')], default='draft', verbose_name='Estado Actual de Orden')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_orders', to='client.ClientModel', verbose_name='Conjunto de Órdenes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
